CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticator') THEN
    CREATE ROLE authenticator WITH LOGIN PASSWORD 'CHANGEME-AUTHENTICATOR' NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sticky') THEN
    CREATE ROLE sticky WITH LOGIN PASSWORD 'CHANGEME-API-KEY' NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS notes (
  uuid UUID PRIMARY KEY,
  v INTEGER NOT NULL DEFAULT 1,
  content TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  style INTEGER NOT NULL DEFAULT 1,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  modified TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  width INTEGER NOT NULL DEFAULT 300,
  height INTEGER NOT NULL DEFAULT 300,
  open BOOLEAN NOT NULL DEFAULT false
);

GRANT sticky TO anon;
GRANT anon TO authenticator;
GRANT sticky TO authenticator;
GRANT USAGE ON SCHEMA public TO sticky, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO sticky;
